server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/data_acquisition?useUnicode=false
    username: root
    password: 1234

  data:
    redis:
      host: redis
      password: 1234
      port: 6379
      lettuce:
        pool:
          max-active: 10      #最大连接
          max-idle: 10        #最大空闲连接
          min-idle: 0         #最小空闲连接
          max-wait: 100ms     #连接等待时间

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: 1234
    virtual-host: my_vhost
    publisher-confirm-type: correlated
    publisher-returns: true
